Repository Hinadt-Inc/miaocha, pull requests merged in 2025-07, with the labels that each got.

#45 [ISSUE #38] 超级管理员不可修改, 管理员无法修改非当前管理员信息
  .gitignore
  miaocha-ui/frontend/src/pages/system/UserManagement/components/UserFormModal.tsx
  miaocha-ui/frontend/src/pages/system/UserManagement/hooks/useTableConfig.tsx
  miaocha-ui/frontend/src/pages/system/UserManagement/hooks/useUserActions.ts
  miaocha-ui/frontend/vite.config.ts
Labels: deploy to inner test k8s env

#48 [ISSUE #47] 优化 README 文件样式
  README.md
  test_handle_insert_table.md
Labels: no ci

#72 [ISSUE #62]优化getColumns调用逻辑，增加防抖机制以避免重复请求，并添加组件卸载时的清理工作
  miaocha-ui/frontend/src/pages/Home/Sider.tsx
Labels: deploy to inner test k8s env

#73 [ISSUE #65]字段百分比实时变化
  miaocha-ui/frontend/src/pages/Home/FieldListItem.tsx
  miaocha-ui/frontend/src/pages/Home/Sider.module.less
  miaocha-ui/frontend/src/pages/Home/Sider.tsx
Labels: deploy to inner test k8s env

#75 [ISSUE #66] 优化模版管理SQL执行模板
  miaocha-ui/frontend/src/utils/logstashTemplates.ts
Labels: deploy to inner test k8s env

#71 [ISSUE #63]优化小屏幕下表格显示，调整列宽和滚动条样式
  miaocha-ui/frontend/src/pages/Home/VirtualTable.module.less
  miaocha-ui/frontend/src/pages/Home/VirtualTable.tsx
Labels: deploy to inner test k8s env

#74 [ISSUE #70] logstash进程信息以模块名称进行排序
  .github/workflows/cicd.yml
  .github/workflows/pr-cleanup.yml
  miaocha-server/src/main/resources/mapper/LogstashProcessMapper.xml
Labels: deploy to inner test k8s env, no ci

#82 [ISSUE #79] 日志查询关键字语法支持 `-` 排除关键字
  .github/workflows/pr-title-check.yml
  miaocha-server/src/main/java/com/hinadt/miaocha/application/service/sql/builder/DetailSqlBuilder.java
  miaocha-server/src/main/java/com/hinadt/miaocha/application/service/sql/builder/DistributionSqlBuilder.java
  miaocha-server/src/main/java/com/hinadt/miaocha/application/service/sql/builder/FieldDistributionSqlBuilder.java
  miaocha-server/src/main/java/com/hinadt/miaocha/application/service/sql/builder/FieldExpressionParser.java
  miaocha-server/src/main/java/com/hinadt/miaocha/application/service/sql/builder/KeywordConditionBuilder.java
  miaocha-server/src/main/java/com/hinadt/miaocha/application/service/sql/expression/ExpressionToken.java
  miaocha-server/src/main/java/com/hinadt/miaocha/application/service/sql/expression/ExpressionTokenizer.java
  miaocha-server/src/main/java/com/hinadt/miaocha/application/service/sql/expression/FieldExpressionParser.java
  miaocha-server/src/main/java/com/hinadt/miaocha/application/service/sql/expression/SqlFragment.java
  miaocha-server/src/main/java/com/hinadt/miaocha/application/service/sql/processor/ResultProcessor.java
  miaocha-server/src/main/java/com/hinadt/miaocha/application/service/sql/search/SearchMethod.java
  miaocha-server/src/test/java/com/hinadt/miaocha/integration/logsearch/LogSearchIntegrationTest.java
  miaocha-server/src/test/java/com/hinadt/miaocha/mock/service/sql/builder/FieldExpressionParserTest.java
  miaocha-server/src/test/java/com/hinadt/miaocha/mock/service/sql/builder/KeywordConditionBuilderTest.java
  miaocha-server/src/test/java/com/hinadt/miaocha/mock/service/sql/expression/ExpressionSyntaxTest.java
Labels: deploy to inner test k8s env

#81 [ISSUE #80]优化排序逻辑，处理空值和数字类型比较
  miaocha-ui/frontend/src/pages/Home/VirtualTable.tsx
  miaocha-ui/frontend/src/pages/SQLEditor/components/ResultsViewer.tsx
Labels: deploy to inner test k8s env

#84 [ISSUE #83] 修复柱形图时间选择问题
  miaocha-ui/frontend/src/pages/Home/SearchBar.tsx
Labels: deploy to inner test k8s env

#115 [ISSUE #111] 移除首页字段列，数据随时更新
  miaocha-ui/frontend/src/pages/Home/Log.tsx
  miaocha-ui/frontend/src/pages/Home/VirtualTable.module.less
  miaocha-ui/frontend/src/pages/Home/VirtualTable.tsx
  miaocha-ui/frontend/src/pages/Home/index.tsx
Labels: deploy to inner test k8s env
